name: eu_quero_carros
description: Desafio teste envolvendo um listagem de carros e a sinalização de interesse através de reservas.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.0
  cupertino_icons: ^1.0.2
  # Injeção de dependências
  get_it: 7.6.7
  # Gerenciador de estados
  bloc: ^8.1.3
  flutter_bloc: 8.1.4
  equatable: ^2.0.5
  # Identificador de conectividade
  internet_connection_checker: ^1.0.0+1
  # HTTP
  dio: ^5.4.1
  # Armazenamento local
  sqflite: ^2.3.2
  # Internacionalização e conversão
  intl: ^0.19.0
  # Background
  flutter_local_notifications: ^17.0.0
  background_fetch: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
